export const cs = {
  _Language: "Čeština",
  Language: "Jazyk",
  DarkMode: "Tmavý režim",
  DeleteCache: "Vymazat mezipaměť",
  ScanAndPlay: "Naskenuj a hraj",
  Play: "Hrát",
  Version: "Verze",
  LibrariesVersion: "Verze knihoven",
  Collection: "Moje kolekce",
  CheckForUpdates: "Zkontroluj aktualzace",
  AvailableUpdates: "Dostupné aktualizace",
  checkUpdatesError:
    "Během ověřování aktualizací nastala chyba. Zkontrolujte si prosím internetové připojení nebo zkuste akci později.",
  upToDate: "Všechny hry jsou již na nejnovější verzi",
  close: "Zavřít",
  gameUpdated: "Hra byla aktualizována",
  gameUpdateError: "Během aktualizace došlo k chybě",
  soundProfile: "Zvukový profil",
  silent: "Tichý",
  effectsOnly: "Pouze efeky",
  effectsMusic: "Efekty + Hudba",
};
