export const de = {
  _Language: "Deutsch",
  Language: "Sprache",
  DarkMode: "Dunkler Modus",
  DeleteCache: "Cache löschen",
  ScanAndPlay: "Scannen und spielen",
  Play: "Spielen",
  Version: "Version",
  LibrariesVersion: "Bibiothek Version",
  Collection: "Meine Sammlung",
  CheckForUpdates: "Auf Updates prüfen",
  AvailableUpdates: "Verfügbare Updates",
  checkUpdatesError: "Fehler währen Updatesprüfung. Testen Sie bitte Ihre Internetverbindung oder versuchen es wieder später.",
  upToDate: "Alle Spiele sind auf der neueste Version",
  close: "Schliesen",
  gameUpdated: "Das Spiel war aktualisiert",
  gameUpdateError: "Es gab ein Fehler während die Aktualisation",
  soundProfile: "Klangprofil",
  silent: "Leise",
  effectsOnly: "Nur Effekte",
  effectsMusic: "Effekte + Musik",
};
