export const en = {
  _Language: "English",
  Language: "Language",
  DarkMode: "Dark mode",
  DeleteCache: "Delete cache",
  ScanAndPlay: "Scan & play",
  Play: "play",
  Version: "Version",
  LibrariesVersion: "Libraries version",
  Collection: "My collection",
  DevelopedBy: "Created by",
  CheckForUpdates: "Check for updates",
  AvailableUpdates: "Available updates",
  checkUpdatesError: "Error while checking updates. Please check your internet connection or try again later.",
  upToDate: "All games are up to date",
  close: "Close",
  gameUpdated: "The game was updated",
  gameUpdateError: "There was an error during the update",
  soundProfile: "Sound profile",
  silent: "Silent",
  effectsOnly: "Only Effects",
  effectsMusic: "Effects + Music",
};
